<a href="https://colab.research.google.com/github/brunobobadilla06/Practica---Ciencia-de-Datos-I/blob/main/Practica_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Configuracion Inicial
import pandas as pd
# URL del archivo CSV
url = 'https://raw.githubusercontent.com/brunobobadilla06/Practica---Ciencia-de-Datos-I/refs/heads/main/Practica%20Data%20Frame%20N%202.csv'

df_stocks = pd.read_csv(url)

In [2]:
# Mostramos las filas y columnas
df_stocks

,formatted_date,MCD,SBUX,GOOG,AMZN,MSFT,JPM,BAC,C,MAR,HLT,RCL,V,MA,PYPL
0,2016-01-01,106.332146,54.353962,742.950012,587.000000,49.853489,50.424938,12.573010,36.897804,57.754189,35.192841,74.235298,71.574371,85.822624,36.139999
1,2016-02-01,100.671043,52.064243,697.770020,552.520020,46.043667,48.033066,11.132540,33.707108,64.228912,41.061607,67.360649,69.556580,83.956566,38.139999
2,2016-03-01,108.782211,53.571442,744.950012,593.640015,50.339031,50.524323,12.021718,36.223217,67.336624,44.499886,74.790009,73.631477,91.278160,38.599998
3,2016-04-01,109.483307,50.457645,693.010010,659.590027,45.453705,53.919910,12.995729,40.153545,66.305466,43.716049,70.465584,74.363144,93.683258,39.180000
4,2016-05-01,105.648926,49.255203,735.719971,722.789978,48.306515,56.098225,13.201019,40.447887,62.474155,41.198154,70.456474,75.999847,92.817329,37.790001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,2021-07-01,240.055786,120.441193,2704.419922,3327.590088,283.846313,150.006454,37.981613,66.635887,145.979996,131.449997,76.870003,245.622177,384.999420,275.529999
67,2021-08-01,234.863205,116.533272,2909.239990,3470.790039,300.752960,158.991928,41.338173,71.392593,135.139999,124.860001,82.730003,228.386063,345.793121,288.660004
68,2021-09-01,239.780670,109.836403,2665.310059,3285.040039,281.405182,162.709534,42.031269,69.675041,148.089996,132.110001,88.949997,222.358551,347.241272,260.209991
69,2021-10-01,244.196198,105.614609,2965.409912,3372.429932,331.014404,168.872391,47.551128,68.662384,160.020004,143.949997,84.430000,211.397858,335.096588,232.589996
70,2021-11-01,243.251434,109.169281,2849.040039,3507.070068,329.986298,158.830002,44.256985,63.700001,147.559998,135.070007,69.820000,193.429489,314.920013,184.889999

In [3]:
# Mostramos informacion general del data frame
df_stocks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   formatted_date  71 non-null     object
 1   MCD             71 non-null     float64
 2   SBUX            71 non-null     float64
 3   GOOG            71 non-null     float64
 4   AMZN            71 non-null     float64
 5   MSFT            71 non-null     float64
 6   JPM             71 non-null     float64
 7   BAC             71 non-null     float64
 8   C               71 non-null     float64
 9   MAR             71 non-null     float64
 10  HLT             71 non-null     float64
 11  RCL             71 non-null     float64
 12  V               71 non-null     float64
 13  MA              71 non-null     float64
 14  PYPL            71 non-null     float64
dtypes: float64(14), object(1)
memory usage: 8.4+ KB

In [6]:
# Convertimos la xolumna date en datetime
df_stocks['formatted_date'] = pd.to_datetime(df_stocks['formatted_date'])

# Miramos si se convirtio en datetime
df_stocks.dtypes['formatted_date']

dtype('<M8[ns]')

In [7]:
# Exploracion basica
# Ver las dimensiones del dataframe
print("Dimesiones del data frame ", df_stocks.shape)

Dimesiones del data frame  (71, 15)

In [8]:
# Columnas disponibles
print("Columnas disponibles ", df_stocks.columns.tolist())

Columnas disponibles  ['formatted_date', 'MCD', 'SBUX', 'GOOG', 'AMZN', 'MSFT', 'JPM', 'BAC', 'C', 'MAR', 'HLT', 'RCL', 'V', 'MA', 'PYPL']

In [9]:
# Obtener estadisticas basicas de las columnas numericas
print(" Estadisticas Basicas")
df_stocks[['MCD', 'SBUX', 'GOOG', 'AMZN', 'MSFT', 'JPM', 'BAC', 'C', 'MAR', 'HLT', 'RCL', 'V', 'MA', 'PYPL']].describe()

 Estadisticas Basicas

,MCD,SBUX,GOOG,AMZN,MSFT,JPM,BAC,C,MAR,HLT,RCL,V,MA,PYPL
count,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000
mean,166.141364,70.467695,1309.236057,1844.628025,133.132113,99.241065,25.946568,56.735507,111.312456,81.478392,90.851429,145.278413,218.651822,115.617464
std,42.876054,22.053342,583.436550,944.397337,77.765768,30.235695,8.089168,10.997466,28.170181,26.520324,22.909133,52.414162,95.469659,75.914087
min,98.913841,45.652046,692.099976,552.520020,45.453705,48.033066,11.132540,33.707108,57.754189,35.192841,31.853811,69.556580,83.956566,36.139999
25%,137.941452,52.327950,934.915009,974.299988,66.861931,80.640980,21.816364,48.657539,89.519512,62.162132,72.517128,94.559734,122.293816,56.109999
50%,165.378510,62.786278,1119.920044,1735.910034,107.740570,96.035423,25.971552,59.150528,122.888184,78.211067,93.269997,143.700562,211.931427,88.760002
75%,202.356850,84.434284,1431.575012,2616.410034,190.287773,109.950825,29.027129,64.777954,133.650467,96.858334,111.008904,190.040054,297.106628,164.619995
max,244.196198,120.441193,2965.409912,3507.070068,331.014404,168.872391,47.551128,77.564484,160.020004,143.949997,131.389603,245.622177,384.999420,291.480011

Agrupacion Groupby

In [14]:
# Agrupacion de componentes fecha
# Necesitamos extraer componentes de fecha
df_stocks['year'] = df_stocks['formatted_date'].dt.year
df_stocks['month'] = df_stocks['formatted_date'].dt.month
df_stocks['day'] = df_stocks['formatted_date'].dt.day
df_stocks['quarter'] = df_stocks['formatted_date'].dt.quarter
df_stocks

,formatted_date,MCD,SBUX,GOOG,AMZN,MSFT,JPM,BAC,C,MAR,HLT,RCL,V,MA,PYPL,year,month,day,Quarter,quarter
0,2016-01-01,106.332146,54.353962,742.950012,587.000000,49.853489,50.424938,12.573010,36.897804,57.754189,35.192841,74.235298,71.574371,85.822624,36.139999,2016,1,1,1,1
1,2016-02-01,100.671043,52.064243,697.770020,552.520020,46.043667,48.033066,11.132540,33.707108,64.228912,41.061607,67.360649,69.556580,83.956566,38.139999,2016,2,1,1,1
2,2016-03-01,108.782211,53.571442,744.950012,593.640015,50.339031,50.524323,12.021718,36.223217,67.336624,44.499886,74.790009,73.631477,91.278160,38.599998,2016,3,1,1,1
3,2016-04-01,109.483307,50.457645,693.010010,659.590027,45.453705,53.919910,12.995729,40.153545,66.305466,43.716049,70.465584,74.363144,93.683258,39.180000,2016,4,1,2,2
4,2016-05-01,105.648926,49.255203,735.719971,722.789978,48.306515,56.098225,13.201019,40.447887,62.474155,41.198154,70.456474,75.999847,92.817329,37.790001,2016,5,1,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,2021-07-01,240.055786,120.441193,2704.419922,3327.590088,283.846313,150.006454,37.981613,66.635887,145.979996,131.449997,76.870003,245.622177,384.999420,275.529999,2021,7,1,3,3
67,2021-08-01,234.863205,116.533272,2909.239990,3470.790039,300.752960,158.991928,41.338173,71.392593,135.139999,124.860001,82.730003,228.386063,345.793121,288.660004,2021,8,1,3,3
68,2021-09-01,239.780670,109.836403,2665.310059,3285.040039,281.405182,162.709534,42.031269,69.675041,148.089996,132.110001,88.949997,222.358551,347.241272,260.209991,2021,9,1,3,3
69,2021-10-01,244.196198,105.614609,2965.409912,3372.429932,331.014404,168.872391,47.551128,68.662384,160.020004,143.949997,84.430000,211.397858,335.096588,232.589996,2021,10,1,4,4
70,2021-11-01,243.251434,109.169281,2849.040039,3507.070068,329.986298,158.830002,44.256985,63.700001,147.559998,135.070007,69.820000,193.429489,314.920013,184.889999,2021,11,1,4,4

In [11]:
ticker_cols = ['MCD', 'SBUX', 'GOOG', 'AMZN', 'MSFT', 'JPM', 'BAC', 'C', 'MAR', 'HLT', 'RCL', 'V', 'MA', 'PYPL']

# Calcular el precio promedio por año para cada ticker (Columnas numericas)
# Agrupamos por año y luego calculamos la media
promedio_anual_tickers = df_stocks.groupby('year')[ticker_cols].mean()
promedio_anual_tickers

,MCD,SBUX,GOOG,AMZN,MSFT,JPM,BAC,C,MAR,HLT,RCL,V,MA,PYPL
year,,,,,,,,,,,,,,
2016,104.280773,51.142220,744.502492,707.225001,51.140350,57.396330,14.090748,40.754643,66.758651,44.944328,69.963773,74.984400,93.404650,38.510833
2017,134.991940,52.246241,928.541667,985.324992,68.682873,82.015368,22.678580,58.288383,101.931187,64.211220,104.028206,95.914673,125.499645,57.047500
2018,153.070151,53.496154,1113.346664,1657.460826,97.693677,99.390544,27.156693,61.179863,125.909911,77.314111,109.080777,130.577713,188.929565,83.079166
2019,187.446757,78.604043,1192.374176,1794.900838,128.960913,107.028756,28.159950,63.182767,129.675998,92.040335,114.404639,165.799440,257.973571,105.914166
2020,193.373987,80.814653,1487.327504,2728.572489,192.007441,100.823367,25.041814,49.861960,102.831286,87.902158,64.045230,191.706842,306.657092,166.795832
2021,228.915776,109.778783,2487.513639,3316.980003,271.868816,153.296657,39.697534,68.091782,143.445455,126.183636,82.925454,218.815499,350.427732,253.879091

In [15]:
# Calcular el precio maximo por trimetre por cada ticker
maximo_trimestral_tickers = df_stocks.groupby(['year', 'quarter'])[ticker_cols].max()
maximo_trimestral_tickers

                     MCD        SBUX         GOOG         AMZN        MSFT  \
year quarter
2016 1        108.782211   54.353962   744.950012   593.640015   50.339031
     2        109.483307   51.435623   735.719971   722.789978   48.306515
     3        102.580368   52.273071   777.289978   837.309998   53.195850
     4        107.785545   52.382828   784.539978   789.820007   57.776409
2017 1        115.617065   53.245609   829.559998   886.539978   61.606422
     2        136.624573   58.005711   964.859985   994.619995   65.329391
     3        143.593903   50.232693   959.109985   987.780029   70.451836
     4        156.343231   53.182014  1046.400024  1176.750000   81.309105
2018 1        155.453079   53.818817  1169.939941  1512.449951   90.310699
     2        153.054428   53.521324  1115.650024  1699.800049   94.581131
     3        154.849365   53.488792  1218.189941  2012.709961  110.119377
     4        174.491272   62.786278  1094.430054  1690.170044  106.768707
2019 1        177.987946   70.699684  1173.310059  1780.750000  114.534332
     2        195.773743   80.094826  1188.479980  1926.520020  130.573273
     3        205.493622   92.257622  1219.000000  1866.780029  135.966339
     4        188.484299   84.742493  1337.020020  1847.839966  154.749725
2020 1        204.088806   81.764160  1434.229980  2008.719971  167.045319
     2        180.017914   75.521713  1428.920044  2758.820068  200.805878
     3        213.309235   84.126076  1634.180054  3450.959961  222.533295
     4        211.316956  105.240311  1760.739990  3256.929932  220.571106
2021 1        220.471207  107.950691  2068.629883  3206.199951  234.348633
     2        232.215759  113.107674  2506.320068  3467.419922  269.888611
     3        240.055786  120.441193  2909.239990  3470.790039  300.752960
     4        244.196198  109.169281  2965.409912  3507.070068  331.014404

                     JPM        BAC          C         MAR         HLT  \
year quarter
2016 1         50.524323  12.573010  36.897804   67.336624   44.499886
     2         56.098225  13.201019  40.447887   66.305466   44.811901
     3         58.466496  14.454847  41.614410   68.132416   47.477150
     4         75.285149  19.958466  51.975777   79.212616   54.422619
2017 1         79.500404  22.288458  52.466637   90.539024   57.002243
     2         80.645424  22.048113  58.815353  103.488274   64.984619
     3         84.735374  23.147448  64.264984  106.690170   68.226303
     4         95.430511  27.080681  66.703407  131.680679   78.613579
2018 1        103.606155  29.447487  69.634354  142.944290   84.313210
     2         97.578163  27.550621  60.820873  132.911270   79.598122
     3        103.863472  28.597004  64.619476  129.188599   79.967651
     4        101.496368  26.384768  58.962799  114.374435   74.780357
2019 1         96.035423  27.167498  58.461689  123.228279   82.592079
     2        106.792931  28.714708  64.571800  138.723206   97.286736
     3        109.903435  28.964279  65.410278  137.506943   96.102249
     4        131.219864  33.469540  74.515808  150.825226  110.740067
2020 1        124.592995  31.368650  69.404449  139.500641  107.634834
     2         93.145775  23.193407  48.487759   90.940002   79.309998
     3         96.837051  24.923790  48.997974  102.910004   90.360001
     4        123.957146  29.553320  59.832924  131.919998  111.260002
2021 1        149.570267  37.959236  71.196068  148.110001  123.680000
     2        162.320847  41.795921  77.564484  148.520004  128.699997
     3        162.709534  42.031269  71.392593  148.089996  132.110001
     4        168.872391  47.551128  68.662384  160.020004  143.949997

                     RCL           V          MA        PYPL
year quarter
2016 1         74.790009   73.631477   91.278160   38.599998
     2         70.465584   75.999847   93.683258   39.180000
     3         68.566833   79.899200   98.711182   40.970001
     4         75.560646   79.715660  103.803398   41.660000
2017 1         90.880608   86.204704  109.521225   43.020000
     2        102.567818   92.373985  119.893608   53.669998
     3        116.367043  102.429604  138.019775   64.029999
     4        116.429375  111.171761  148.180374   75.730003
2018 1        126.115715  121.126724  172.338699   85.320000
     2        102.675056  129.574066  192.969025   83.269997
     3        124.025208  147.051773  218.862717   92.330002
     4        108.501839  138.841415  197.914246   85.809998
2019 1        115.969437  153.570633  232.155273  103.839996
     2        118.314911  170.901917  261.192596  114.459999
     3        113.701927  178.061020  278.157379  110.400002
     4        131.389603  185.610321  295.539124  108.169998
2020 1        115.929268  196.545456  312.711853  113.889999
     2         51.869999  193.140228  298.674133  174.229996
     3         68.839996  210.061218  356.026947  204.139999
     4         78.809998  217.394608  355.197632  234.199997
2021 1         93.269997  211.093323  354.761078  259.850006
     2         93.269997  233.091354  380.676941  291.480011
     3         88.949997  245.622177  384.999420  288.660004
     4         84.430000  211.397858  335.096588  232.589996

In [16]:
# Contar cuantos registros hay en nuestro dataframe por año
conteo_anual = df_stocks.groupby('year').size()
conteo_anual

year
2016    12
2017    12
2018    12
2019    12
2020    12
2021    11
dtype: int64

Agregaciones multiples con .agg()